import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { AppBar, Box, Button, Container, Dialog, DialogContent, Grid, IconButton, Stack, Toolbar, Typography } from '@mui/material'
import { FC, useEffect, useRef, useState } from 'react'
import { useSwipeable } from 'react-swipeable'


export default function Home() {
  const [open, setOpen] = useState(false)

  const [useLargeScreenView, setUseLargeScreenView] = useState(
    typeof window !== 'undefined' && window.innerWidth > 900
  )

  const images = [
    'https://images.unsplash.com/photo-1549471013-3364d7220b75?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
    'https://mir-s3-cdn-cf.behance.net/project_modules/hd/924649116456717.6062730f31de4.jpg',
    'https://mrwallpaper.com/images/hd/tony-hawk-birdman-sky-jump-n1u0z6j7pekpqsqw.jpg',
    'https://t4.ftcdn.net/jpg/06/08/39/23/360_F_608392383_HqSETDqGF4uIGfEWeVPlvnBgu99GCFCG.jpg'
  ]

  useEffect(() => {
    let handleResize = () => {}
    if(typeof window !== 'undefined' ){
      handleResize = () => {
        setUseLargeScreenView(window.innerWidth > 900)
      }
      window.addEventListener('resize', handleResize)
    }

    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [useLargeScreenView])


 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth='md' sx={{display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
        <Button onClick={() => {
                    setOpen(true)
        }}>
          Open gallery view 

        </Button>

  

        <GalleryView useLargeScreenView={useLargeScreenView} images={images} open={open} onClose={() => {
          setOpen(false)
        }}/>
        </Container>


      </main>
    </>
  )
}

interface GalleryViewProps {
  images: string[] // Array of image URLs
  open: boolean // Control to open/close the dialog externally
  onClose: () => void // Function to handle closing of dialog
  useLargeScreenView?: boolean // to seaprate it is mobile view or not
}

const GalleryView: FC<GalleryViewProps> = ({
  images,
  open,
  onClose,
  useLargeScreenView,
}) => {
  const [selectedIndex, setSelectedIndex] = useState<number>(0)
  const [transitionDirection, setTransitionDirection] = useState<
    'left' | 'right' | ''
  >('') // Track swipe direction

  const thumbnailRefs = useRef<(HTMLDivElement | null)[]>([])

  const handleSelectImage = (index: number) => {
    if (index !== 0 && index !== images.length - 1) {
      setTransitionDirection(index > selectedIndex ? 'left' : 'right')
    }

    setSelectedIndex(index)
  }

  // previous
  const handleSwipeLeft = () => {
    if (selectedIndex !== 0) {
      setTransitionDirection('left')
      setSelectedIndex((prevIndex) => prevIndex - 1)
    }
  }

  // next
  const handleSwipeRight = () => {

    if (selectedIndex !== images.length - 1) {
      setTransitionDirection('right')
      setSelectedIndex((prevIndex) => prevIndex + 1)
    }
  }

  // inverted
  const handlers = useSwipeable({
    onSwipedLeft: handleSwipeRight,
    onSwipedRight: handleSwipeLeft,

    trackMouse: true, // Enable mouse swiping as well
  })

  useEffect(() => {
    if (transitionDirection !== '') {
      const timeout = setTimeout(() => setTransitionDirection(''), 200) // Match the CSS transition duration
      return () => clearTimeout(timeout)
    }
  }, [transitionDirection])

  useEffect(() => {
    if (thumbnailRefs.current[selectedIndex]) {
      thumbnailRefs.current[selectedIndex]?.scrollIntoView({
        behavior: 'smooth', // Smooth scroll
        block: 'nearest', // Scroll only enough to make it visible
        inline: 'center', // Center the thumbnail in the view
      })
    }
  }, [selectedIndex])

  return (
    <Dialog
      open={open}
      onClose={onClose}
      fullWidth
      fullScreen={true}
      PaperProps={{
        sx: {
          backgroundColor: 'rgba(0, 0, 0, 0.8)', // Black tint with transparency
          overflowX: 'hidden',
          overflowY: 'hidden', // twitch issue 
        },
      }}
    >
      {/* AppBar with Close Button */}
      <AppBar position="relative" sx={{ backgroundColor: 'black' }}>
        <Toolbar>
          <IconButton
            edge="end"
            color="inherit"
            onClick={onClose}
            aria-label="close"
          >
            {/* <CloseIcon /> */}
            <p color='white'>Close</p>
          </IconButton>
        </Toolbar>
      </AppBar>

      <DialogContent
        sx={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          paddingLeft: useLargeScreenView ? undefined : 0,
          paddingRight: useLargeScreenView ? undefined : 0,
        }}
      >
        {!useLargeScreenView ? (
          <Box
            {...handlers} // Attach swipe handlers to the main image container
            sx={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              flex: 1,
              width: '100%',
              height: '100%',
              touchAction: 'pan-y', // Allow vertical scrolling while swiping
            }}
          >
            <Box
              {...handlers} // Attach swipe handlers to the main image container
              sx={{
                width: '100%',
                height: '65%',
                position: 'absolute',
                transition: 'transform 0.2s ease',
                transform:
                  transitionDirection === 'right'
                    ? 'translateX(100%) translateY(0)'
                    : transitionDirection === 'left'
                    ? 'translateX(-100%) translateY(0)'
                    : 'translateX(0) translateY(0)',
                opacity: transitionDirection ? 0 : 1,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
              }}
            >
              <Image
                unoptimized
                src={images[selectedIndex]}
                alt={`image-${selectedIndex}`}
                width={0}
                height={0}
                style={{
                  height: '100%',
                  width: '100%',
                  objectFit: 'contain',
                }}
              />
            </Box>
          </Box>
        ) : (
          <Box
            sx={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              height: '68%', // twitch
              mb: 2,
            }}
          >
            <Image
              src={images[selectedIndex]}
              unoptimized
              alt="Selected image"
              width={0}
              height={0}
              style={{
                height: '100%',
                width: '100%',
                objectFit: 'contain',
              }}
            />
          </Box>
        )}

        <Container maxWidth="md" disableGutters={!useLargeScreenView} sx={{justifyContent: 'center'}}>
          <Typography
            variant="h6"
            sx={{
              color: 'white',
              textAlign: 'center',
              mb: 2,
            }}
          >
            {`${images.length > 0 ? selectedIndex + 1 : 0}/${images.length}`} 
          </Typography>

          {useLargeScreenView ? (
            <Grid
              columns={6}
              container
              gap={1}
              spacing={1}
              sx={{ justifyContent: 'center', alignItems: 'center', overflowX: 'auto', mt: 2, 


              }}

            >

              {images.map((image, index) => (
                <Grid
                  item
                  xs={1}
                  sm={1}
                  md={1}
                  key={index}
                  sx={{
                    display: 'flex',
                    justifyContent: 'center',
                  }}
                  onClick={() => handleSelectImage(index)}
                >
                  <Image
                  unoptimized
                    src={image}
                    alt={`thumbnail-${index}`}
                    width={0}
                    height={0}
                    style={{
                      height: 120,
                      width: 120,
                      borderRadius: 8,
                      cursor: 'pointer',
                      objectFit: 'cover',
                      border:
                        index === selectedIndex
                          ? '2px solid green'
                          : '2px solid transparent',
                      transition: 'border-color 0.2s',
                    }}
                  />
                </Grid>
              ))}
            </Grid>
          ) : (
            <Stack
              direction={'row'}
              sx={{
                flexDirection: 'row',
                overflowX: 'scroll', // Enable horizontal scrolling
                '&::-webkit-scrollbar': {
                  display: 'none',
                },
              }}
            >
              {images.map((image, index) => (
                <Box
                  key={index}
                  onClick={() => handleSelectImage(index)}
                  ref={(el: HTMLDivElement | null) =>
                    (thumbnailRefs.current[index] = el)
                  }

                >
                  <Image
                    src={image}
                    unoptimized
                    alt={`thumbnail-${index}`}
                    width={120} // Set a fixed width
                    height={120} // Set a fixed height
                    style={{
                      cursor: 'pointer',
                      border:
                        index === selectedIndex
                          ? '2px solid green'
                          : '2px solid transparent',
                      marginRight: index === images.length - 1 ? 50 : 0.5,
                      marginLeft: index === 0 ? 50 : 0.5,
                      transition: 'border-color 0.2s',
                      borderRadius: '8px',
                      objectFit: 'cover',
                    }}
                  />
                </Box>
              ))}
            </Stack>
          )}
        </Container>
      </DialogContent>
    </Dialog>
  )
}

